`ifndef FIFO_MEM_TB__SV
`define FIFO_MEM_TB__SV

  // Generated by tbengy. Created by Prasad Pandit.

  `timescale 10ps/10ps
  `include "uvm_macros.svh"

  `define DELAY 10

  module fifo_mem_tb_uvm;
  import fifo_mem_test_pkg::*;
  import uvm_pkg::*;

    parameter int ENDTIME    = 2000;
    parameter int DATA_WIDTH = 16;
    parameter int OSTD_NUM   = 16;
    //parameter int MAX_INT    = OSTD_NUM;
    //parameter int ADDR_WIDTH = 8;
    //parameter int MEM_SIZE   = 64;
    //parameter int MAX_ADDR   = 32;

  logic clk;
  logic areset_b;

  fifo_mem #(
    .DATA_WIDTH      (DATA_WIDTH),
    .OSTD_NUM        (OSTD_NUM),
    .THRESHOLD_VALUE (OSTD_NUM/2)
  ) u_tb (
    .clk_in        (clk),
    .areset_b      (areset_b),
    .trans_read    (vif.trans_read),
    .trans_write   (vif.trans_write),
    .data_in       (vif.data_in),
    .data_out      (vif.data_out),
    .full_ind      (vif.full_ind),
    .empty_ind     (vif.empty_ind),
    .overflow_ind  (vif.overflow_ind),
    .underflow_ind (vif.underflow_ind),
    .threshold_ind (vif.threshold_ind)
  );

  fifo_mem_intf #(
    .DATA_WIDTH (DATA_WIDTH)
  ) vif(
    .clk      (clk),
    .areset_b (areset_b)
    );

  // From auto-gen
  //fifo_mem DUT (
  //  .clk(clk),
  //  .we(intf.we),
  //  .addr(intf.addr),
  //  .wdata(intf.wdata),
  //  .rdata(intf.rdata)
  //);

  initial begin
    clk      = 1'b0;
    areset_b = 1'b0;
  end

  initial begin
    $dumpfile("fifo_mem_uvm.vcd");
    $dumpvars();
    main;
  end

  task static main;
    fork
      clock_gen;
      reset_gen;
    join
  endtask

  task static clock_gen;
    begin
      forever #`DELAY clk = ~clk;
    end
  endtask

  task static reset_gen;
    begin
      #(`DELAY*2)
      areset_b = 1'b1;
      # 18
      areset_b = 1'b0;
      # (`DELAY*2)
      areset_b = 1'b1;
    end
  endtask

  initial begin
    uvm_config_db #(virtual fifo_mem_intf)::set(null, "*", "vintf", vif);
    run_test();
    //uvm_root #(.run_test("fifo_gpt_test")) run_test();
  end
  endmodule

`endif

// End of fifo_mem_tb
