`ifndef FIFO_MEM_TB__SV
`define FIFO_MEM_TB__SV

  // Generated by tbengy. Created by Prasad Pandit.

  `timescale 1ns/1ps
  `include "uvm_macros.svh"

  module fifo_mem_tb;
    import fifo_mem_test_pkg::*;
    import uvm_pkg::*;

    logic clk;

    fifo_mem_intf intf(.clk(clk));

    fifo_mem DUT (
      .clk(clk),
      .we(intf.we),
      .addr(intf.addr),
      .wdata(intf.wdata),
      .rdata(intf.rdata)
    );

    initial begin
      clk = 0;
      forever begin
        #10 clk = ~clk;
      end
    end

    initial begin
      uvm_config_db #(virtual fifo_mem_intf)::set(null, "*", "vintf", intf);
      run_test();
    end
  endmodule

`endif

//End of fifo_mem_tb
